apiVersion: v1alpha1
sts-region: ap-south-1
customNamespace:
  - name: custom_metric
    namespace: custom_metric
    regions:
      - ap-south-1
    metrics:
      - name: FunctionSuccess
        statistics:
          - Sum
        period: 10
        length: 300
